# Form implementation generated from reading ui file 'categories_design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 300)
        Form.setMinimumSize(QtCore.QSize(350, 300))
        Form.setMaximumSize(QtCore.QSize(350, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.categoriesList = QtWidgets.QListWidget(parent=Form)
        self.categoriesList.setObjectName("categoriesList")
        self.verticalLayout.addWidget(self.categoriesList)
        self.addCategoryButton = QtWidgets.QPushButton(parent=Form)
        self.addCategoryButton.setObjectName("addCategoryButton")
        self.verticalLayout.addWidget(self.addCategoryButton)
        self.deleteCategoryButton = QtWidgets.QPushButton(parent=Form)
        self.deleteCategoryButton.setObjectName("deleteCategoryButton")
        self.verticalLayout.addWidget(self.deleteCategoryButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Категории"))
        self.addCategoryButton.setText(_translate("Form", "Добавить категорию"))
        self.deleteCategoryButton.setText(_translate("Form", "Удалить категорию"))
