# Form implementation generated from reading ui file 'tasks_design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 550)
        Form.setMinimumSize(QtCore.QSize(350, 450))
        Form.setMaximumSize(QtCore.QSize(450, 650))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tasksList = QtWidgets.QListWidget(parent=Form)
        self.tasksList.setObjectName("tasksList")
        self.verticalLayout_2.addWidget(self.tasksList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.filterCategory = QtWidgets.QComboBox(parent=Form)
        self.filterCategory.setObjectName("filterCategory")
        self.horizontalLayout.addWidget(self.filterCategory)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.taskName = QtWidgets.QLineEdit(parent=Form)
        self.taskName.setObjectName("taskName")
        self.verticalLayout.addWidget(self.taskName)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.taskDescription = QtWidgets.QTextEdit(parent=Form)
        self.taskDescription.setObjectName("taskDescription")
        self.verticalLayout.addWidget(self.taskDescription)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectCategory = QtWidgets.QComboBox(parent=Form)
        self.selectCategory.setObjectName("selectCategory")
        self.horizontalLayout_2.addWidget(self.selectCategory)
        self.categoriesButton = QtWidgets.QPushButton(parent=Form)
        self.categoriesButton.setObjectName("categoriesButton")
        self.horizontalLayout_2.addWidget(self.categoriesButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.addTaskButton = QtWidgets.QPushButton(parent=Form)
        self.addTaskButton.setObjectName("addTaskButton")
        self.verticalLayout.addWidget(self.addTaskButton)
        self.deleteTaskButton = QtWidgets.QPushButton(parent=Form)
        self.deleteTaskButton.setObjectName("deleteTaskButton")
        self.verticalLayout.addWidget(self.deleteTaskButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Список задач"))
        self.label_5.setText(_translate("Form", "Фильтр по категориям:"))
        self.label_2.setText(_translate("Form", "Название задачи"))
        self.label_3.setText(_translate("Form", "Описание"))
        self.label.setText(_translate("Form", "Категория"))
        self.categoriesButton.setText(_translate("Form", "Категории"))
        self.addTaskButton.setText(_translate("Form", "Добавить задачу"))
        self.deleteTaskButton.setText(_translate("Form", "Удалить задачу"))
